### ISSUE TITLE
b'IO error: ./.statedb/tbears: Input/output error' on tbears start.

### ISSUE THREAD

**Issue by Syed-Osama-Hussain** [icon-project/t-bears#75]
Hello. I'm following along with the documentation to get familiar with icon on icondev.io and I've encountered an error `b'IO error: ./.statedb/tbears: Input/output error'` when running tbears start. I installed tbears for Ubuntu as written in the readme file. Following is the complete trace back:
```
Traceback (most recent call last):
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/aiormq/connection.py", line 237, in connect
    res = await self.__receive_frame()
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/aiormq/connection.py", line 326, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/usr/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 1 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/iconservice/icon_service.py", line 210, in <module>
    main()
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/iconservice/icon_service.py", line 157, in main
    _run_async(_check_rabbitmq(conf[ConfigKey.AMQP_TARGET]))
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/iconservice/icon_service.py", line 171, in _run_async
    return loop.run_until_complete(async_func)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/iconservice/icon_service.py", line 179, in _check_rabbitmq
    connection = await aio_pika.connect(host=amqp_target, login=amqp_user_name, password=amqp_password)
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/aio_pika/connection.py", line 324, in connect
    timeout=timeout, client_properties=client_properties, loop=loop
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/aio_pika/connection.py", line 125, in connect
    timeout=timeout
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/aio_pika/connection.py", line 108, in _make_connection
    connection = await aiormq.connect(self.url, **kwargs)
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/aiormq/connection.py", line 527, in connect
    await connection.connect(client_properties or {})
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/aiormq/connection.py", line 241, in connect
    raise exc.IncompatibleProtocolError(*e.args) from e
aiormq.exceptions.IncompatibleProtocolError: 0 bytes read on a total of 1 expected bytes
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/__main__.py", line 23, in <module>
    sys.exit(main())
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/block_manager.py", line 627, in main
    block_manager = BlockManager(conf=conf)
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/block_manager.py", line 140, in __init__
    self._block: 'Block' = Block(f'{conf["stateDbRootPath"]}/tbears')
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/block.py", line 37, in __init__
    self._db: TbearsDB = TbearsDB(TbearsDB.make_db(db_path))
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/tbears_db.py", line 24, in make_db
    return plyvel.DB(path, create_if_missing=create_if_missing)
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: b'IO error: ./.statedb/tbears: Input/output error'
Started tbears service successfully
````

**Comment by eunsoo-icon** [comment]
Check the earlgrey version with this command `pip show earlgrey`.

If earlgrey version is 0.1.0 then downgrade with this command `pip install -U earlgrey == 0.0.4`.

We are working on releasing a T-Bear that is compatible with earlgrey 0.1.0

**Comment by Syed-Osama-Hussain** [comment]
I downgraded earlgrey to 0.0.4 but the error still persists.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/__main__.py", line 23, in <module>
    sys.exit(main())
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/block_manager.py", line 627, in main
    block_manager = BlockManager(conf=conf)
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/block_manager.py", line 140, in __init__
    self._block: 'Block' = Block(f'{conf["stateDbRootPath"]}/tbears')
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/block.py", line 37, in __init__
    self._db: TbearsDB = TbearsDB(TbearsDB.make_db(db_path))
  File "/home/osama/icon-app/env/lib/python3.6/site-packages/tbears/block_manager/tbears_db.py", line 24, in make_db
    return plyvel.DB(path, create_if_missing=create_if_missing)
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: b'IO error: ./.statedb/tbears: Input/output error'
Started tbears service successfully
```

**Comment by eunsoo-icon** [comment]
This error occurred while initializing the level DB open or create.

plyvel IOError is caused by system environment such as directory permissions.

Check the environment

**Comment by chaudharypraveen98** [comment]
I am also stuck with this problem. I am using debian on wsl. Has anyone resolved the problem?
