### ISSUE TITLE
t bears server error on deploying or scoreapi commands in Docker

### ISSUE THREAD

**Issue by aymusbond** [icon-project/t-bears#79]
Till a day ago everything was working very well but suddenly when I continued working in the Docker Container today, I get this error when I try to deploy, re deploy or find the scoreapi of the Deployed SCORE. I tried stopping and starting t bears and even clearing all the smart contracts but still I see the below error when I try to deploy a SCORE on the testnet.

WARNING:root:Message returned. Probably destination queue does not exists: ReturnedMessage:{'app_id': None,
 'body_size': 4915,
 'cluster_id': None,
 'consumer_tag': None,
 'content_encoding': None,
 'content_type': None,
 'correlation_id': b'140039276967752',
 'delivery_mode': 1,
 'delivery_tag': None,
 'exchange': '',
 'expiration': None,
 'headers': {'From': 'amq_PNe4nvGzrjKKHx4m3FZgdS',
             'FuncName': 'IconScoreInnerTask.query'},
 'message_id': None,
 'priority': 128,
 'redelivered': None,
 'reply_to': 'amq_PNe4nvGzrjKKHx4m3FZgdS',
 'routing_key': 'IconScore.loopchain_default.7100',
 'synchronous': False,
 'timestamp': 1599377127,
 'type': 'call',
 'user_id': None}
ERROR:jsonrpcserver.request:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/request.py", line 39, in handle_exceptions
    yield
  File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/async_request.py", line 21, in call
    result = await callable_(*(self.args or []), **(self.kwargs or {}))
  File "/usr/local/lib/python3.7/site-packages/iconrpcserver/dispatcher/v3d/version3d.py", line 78, in debug_estimateStep
    response = await score_stub.async_task().query(request)
  File "/usr/local/lib/python3.7/site-packages/earlgrey/message_queue_stub.py", line 128, in _call_async_rpc
    result = await self._rpc_client_async.call(func_name, kwargs=params.arguments, priority=priority)
  File "/usr/local/lib/python3.7/site-packages/earlgrey/patterns/rpc/client_async.py", line 131, in call
    return (yield from future)
aio_pika.pika.exceptions.UnroutableError: 1 unroutable message(s) returned

Raised JSONRPCException while returning the custom response. Error message: {'code': -32000, 'message': 'Server error'}
Traceback (most recent call last):
  File "/usr/local/bin/tbears", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tbears/tbears_cli.py", line 25, in main
    result = cmd.run(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/tbears/command/command.py", line 72, in run
    result = self.cmdScore.run(args)
  File "/usr/local/lib/python3.7/site-packages/tbears/command/command_score.py", line 92, in run
    return getattr(self, args.command)(conf)
  File "/usr/local/lib/python3.7/site-packages/tbears/command/command_score.py", line 136, in deploy
    step_limit = icon_service.estimate_step(deploy_transaction) + 10000
  File "/usr/local/lib/python3.7/site-packages/iconsdk/icon_service.py", line 282, in estimate_step
    result = self.__provider.make_request('debug_estimateStep', params)
  File "/usr/local/lib/python3.7/site-packages/iconsdk/providers/http_provider.py", line 129, in make_request
    custom_response = self._return_custom_response(response, full_response)
  File "/usr/local/lib/python3.7/site-packages/iconsdk/providers/http_provider.py", line 154, in _return_custom_response
    raise JSONRPCException(content_as_dict["error"])
iconsdk.exception.JSONRPCException: {'code': -32000, 'message': 'Server error'} (Json rpc error)

**Comment by eunsoo-icon** [comment]
T-Bears has 3 components
- block_manager
- ICON Service
- ICON RPC Server

The above error messages indicate that the ICON Server is down and ICON RPC server could not send a message to the ICON Service.

Give me your deploy command. I want to reproduce error with your command.

I succeed to deploy a SCORE with below command to testnet(Euljiro)
`tbears deploy score_test -k keystore -u https://test-ctz.solidwallet.io/api/v3`
