### ISSUE TITLE
Unable to run any tbears command in macOS

### ISSUE THREAD

**Issue by biraj094** [icon-project/t-bears#85]
[requirements.txt](https://github.com/icon-project/t-bears/files/6400145/requirements.txt)

This is the requirements.txt that was generated after I followed every single step in the tutorial. 

Traceback (most recent call last):
  File "/Users/apple/Desktop/Github/icx_icon/icon-test/env/bin/tbears", line 5, in <module>
    from tbears import main
  File "/Users/apple/Desktop/Github/icx_icon/icon-test/env/lib/python3.8/site-packages/tbears/__init__.py", line 15, in <module>
    from .tbears_cli import main
  File "/Users/apple/Desktop/Github/icx_icon/icon-test/env/lib/python3.8/site-packages/tbears/tbears_cli.py", line 17, in <module>
    from tbears.command.command import Command
  File "/Users/apple/Desktop/Github/icx_icon/icon-test/env/lib/python3.8/site-packages/tbears/command/command.py", line 22, in <module>
    from tbears.command.command_wallet import CommandWallet
  File "/Users/apple/Desktop/Github/icx_icon/icon-test/env/lib/python3.8/site-packages/tbears/command/command_wallet.py", line 30, in <module>
    from iconsdk.utils import add_0x_prefix
ImportError: cannot import name 'add_0x_prefix' from 'iconsdk.utils' (/Users/apple/Desktop/Github/icx_icon/icon-test/env/lib/python3.8/site-packages/iconsdk/utils/__init__.py)

**Comment by eunsoo-icon** [comment]
This problem was fixed with this [commit](https://github.com/icon-project/t-bears/commit/338dee91368d2bbf5a5327f27f90225f45f11b7b)

Use latest T-Bears 1.8.0

**Comment by biraj094** [comment]
@eunsoo-icon  Thanks for the prompt reply. However, I am unable to install the latest version using `pip install tbears`. It wouldn't work even if I added the version explicitly. Even if I try to upgrade it to tbears==1.7.1 or iconservice==1.7.3 it does not work. I am using the latest pip and python3.8 .
![Screen Shot 2021-04-30 at 9 15 10 AM](https://user-images.githubusercontent.com/19893103/116645140-e0668080-a994-11eb-9551-26c11dd10507.png)

**Comment by eunsoo-icon** [comment]
Now, iconservice and tbears support python3.7 only

Please downgrade your python to 3.7

I will update 'Requirements' in README.
