### ISSUE TITLE
Issue when call bears in CLI

### ISSUE THREAD

**Issue by quochuynh67** [icon-project/t-bears#87]
Hi I have a problem when I try to use tbears the issue like below

 tbears
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/tbears", line 6, in <module>
    from tbears import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tbears/__init__.py", line 15, in <module>
    from .tbears_cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tbears/tbears_cli.py", line 17, in <module>
    from tbears.command.command import Command
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tbears/command/command.py", line 22, in <module>
    from tbears.command.command_wallet import CommandWallet
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tbears/command/command_wallet.py", line 33, in <module>
    from iconservice.base.address import is_icon_address_valid
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/iconservice/__init__.py", line 26, in <module>
    from .iconscore.icon_container_db import VarDB, DictDB, ArrayDB
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/iconservice/iconscore/icon_container_db.py", line 20, in <module>
    from .db import IconScoreDatabase, Key, KeyType
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/iconservice/iconscore/db.py", line 25, in <module>
    from ..database.db import (
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/iconservice/database/db.py", line 18, in <module>
    import plyvel
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/_plyvel.cpython-37m-darwin.so, 2): Symbol not found: __ZTIN7leveldb10ComparatorE
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/_plyvel.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyvel/_plyvel.cpython-37m-darwin.so

**Comment by eunsoo-icon** [comment]
Please let me know followings
1. T-Bears version : `pip show tbears`
2. plyvel verison :  `pip show plyvel`

**Comment by quochuynh67** [comment]
Hi @eunsoo-icon 

---------- plyvel -----------
Name: plyvel
Version: 1.2.0
Summary: Plyvel, a fast and feature-rich Python interface to LevelDB
Home-page: https://github.com/wbolster/plyvel
Author: Wouter Bolsterlee
Author-email: wouter@bolsterl.ee
License: BSD License
Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Requires: 
Required-by: iconservice



----------- tears ----------------
Name: tbears
Version: 1.8.0
Summary: Test suite for ICON SCORE development
Home-page: https://github.com/icon-project/t-bears
Author: ICON Foundation
Author-email: foo@icon.foundation
License: Apache License 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Requires: iconservice, iconsdk, iconrpcserver, ipython

**Comment by quochuynh67** [comment]
This is the way I use PIP to install

But I can run tears successful when I use Docker container. But I don't know how to edit the python code (after tbears init name Name)

**Comment by eunsoo-icon** [comment]
Check this link. https://githubmemory.com/repo/wbolster/plyvel/issues/114

**Comment by quochuynh67** [comment]
Nothing happen :))) I tried to use leveldb 1.22 like the link you sent me.
